id: P006796
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W24041
  title: བདེ་བར་གཤེགས་པའི་སྐུ་གཟུགས་ཀྱི་ཚད་ཀྱི་རབ་ཏུ་བྱེད་པ་ཡིད་བཞིན་ནོར་བུ
  author: ''
  volumes:
    074174785d4c45df835640250fe30629:
      image_group_id: I3652
      title: ''
      volume_number: 1
      total_pages: 126
      base_file: v001.txt
