id: I6D4A05A9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T00:22:48+00:00'
last_modified: '2022-06-08T06:55:09.241308+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W24041
  title: བདེ་བར་གཤེགས་པའི་སྐུ་གཟུགས་ཀྱི་ཚད་ཀྱི་རབ་ཏུ་བྱེད་པ་ཡིད་བཞིན་ནོར་བུ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8B89:
      image_group_id: I3652
      title: ''
      total_pages: 126
      order: 1
      base_file: 8B89.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
